### ISSUE TITLE
Order not respected in union of types including str

### ISSUE THREAD

**Issue by maurosilber** [dapper91/pydantic-xml#127]
According to the docs, the order of the types in the union is respected. But when using `str`, it seems that it always wins:

```python
from pydantic_xml import BaseXmlModel, attr

class Model(BaseXmlModel):
    x: float | bool = attr()
    y: bool | float = attr()
    z: str | float = attr()
    w: float | str = attr()

Model.from_xml("<Model x='1' y='1' z='1' w='1' />")
```
Output:
```python
Model(x=1.0, y=True, z='1', w='1')
```
Expected:
```python
Model(x=1.0, y=True, z='1', w=1.0)
```

**Comment by dapper91** [comment]
@maurosilber Hi.

The order of the types in the union is respected except the case when the input type matches one of the union types. I agree that is not very intuitive but that is how `pydantic` itself works. [Here](https://docs.pydantic.dev/latest/api/standard_library_types/#union) you can read more about that. 

I will mention that in the documentation, thanks.

To fix you problem pass `left_to_right` union_mode to the `w` field:

```python
class Model(BaseXmlModel):
    x: float | bool = attr()
    y: bool | float = attr()
    z: str | float = attr()
    w: float | str = attr(union_mode='left_to_right')
```

**Comment by maurosilber** [comment]
Thank you!

I was not aware of that behaviour, as I'm not quite familiar with `pydantic`.

I've opened a PR updating the docs.
