### ISSUE TITLE
Support for raw XML?

### ISSUE THREAD

**Issue by arjenzorgdoc** [dapper91/pydantic-xml#14]
Is there a way to include raw XML for some properties.

Maybe something like this:

```python
class Widget(BaseXmlModel):
    id: str = attr()
    body: etree.Element = element()
```

**Comment by dapper91** [comment]
Implemented in version 2.1.0.

[See](https://pydantic-xml.readthedocs.io/en/latest/pages/data-binding/raw.html) for more information.
