### ISSUE TITLE
Pydantic pattern constraint not supported

### ISSUE THREAD

**Issue by jordancrane-truework** [dapper91/pydantic-xml#142]
Given the following example code:

```python
from pydantic_xml import BaseXmlModel, element

class TestXmlModel(BaseXmlModel, tag="Test"):
    field: str = element(tag="Field", pattern=r"/d+")

TestXmlModel(field="1234")
```

The following error occurs:

`pydantic_xml.errors.ModelError: type chain is not supported`

It works fine with other constraint types that I have tried (`max_length`, `min_length`).

**Comment by dapper91** [comment]
@jordancrane-truework Hi. I think you made a mistake. regexp digit is `\d` not `/d`. This should work:

```python
from pydantic_xml import BaseXmlModel, element

class TestXmlModel(BaseXmlModel, tag="Test"):
    field: str = element(tag="Field", pattern=r"\d+")

TestXmlModel(field="1234")
```

**Comment by jordancrane-truework** [comment]
@dapper91 Oops, you're correct, dumb mistake on my part - thanks for the correction. Unfortunately even with the correct regex I still get the same error.

**Comment by dapper91** [comment]
@jordancrane-truework Hmm. That code works perfect on my side. Please, could you provide pydantic-xml, pydantic and pydantic-core versions you are using.
