### ISSUE TITLE
[Question] Disable namespace inheritance

### ISSUE THREAD

**Issue by elio2t** [dapper91/pydantic-xml#197]
First, thank you for this very helpful lib!

I found that in the [docs](https://pydantic-xml.readthedocs.io/en/latest/pages/data-binding/elements.html#namespaces):
"The namespace and namespace mapping can be declared for a model. In that case all fields [except attributes](https://pydantic-xml.readthedocs.io/en/latest/pages/data-binding/attributes.html#namespace-inheritance) inherit them"

Simple question: is it possible to disable this behaviour ?
As a workaround I set `ns=""`for all children elements but it's not ideal :)

**Comment by dapper91** [comment]
@elio2t Hi,

Right now there is no way to disable it. The only way to set it manually.
