### ISSUE TITLE
list of discriminated unions

### ISSUE THREAD

**Issue by A-Debord** [dapper91/pydantic-xml#206]
hi,

I'm trying to parse a list of discriminated unions but it doesn't seem to be implemented.
Is there a workaround ? or maybe I'm not doing it properly ?

```py

class FloatData(BaseXmlModel):
    '''group data'''
    id: str = attr(tag='name')
    type: Literal['float'] = attr()
    data: Floats


class StringData(BaseXmlModel):
    '''group data'''
    id: str = attr(tag='name')
    type: Literal['string'] = attr()
    data: str


DataTypes = Annotated[Union[FloatData, StringData], Field(discriminator='type')]

class Doc(BaseXmlModel):
    data_list: list[DataTypes] = element(tag='data', default=[])
```

**Comment by dapper91** [comment]
@A-Debord Hi,

That's a bug, I will fix it in the next release.

**Comment by dapper91** [comment]
Fixed in version 2.12.1

**Comment by A-Debord** [comment]
Okay, thanks for the answer !

Le lun. 26 août 2024, 18:55, Dmitry Pershin ***@***.***> a
écrit :

**Comment by GaNiziolek** [comment]
Man, that's funny, I caught exactly this error last week, and I was already making a fork to write a PR lol.
Good to see this is now fixed.
Thanks!
