### ISSUE TITLE
[Question] How to handle a nillable wrapped?

### ISSUE THREAD

**Issue by ReinderVosDeWael** [dapper91/pydantic-xml#211]
I have an XML which contains a potentially empty list (see example code below). I'm trying to write a XML model that can read this list both in the empty case and in the case where it contains data. I've written the test-case below, but I'm not able to find any way of parsing both XMLs in this code with a single model. Could you help me on my way?

```python
import pydantic_xml

xml_none = """
<Top>
<Property />
</Top>
"""

xml_list_int = """
<Top>
<Property>
<int>1</int>
<int>2</int>
</Property>
</Top>
"""

class Top(pydantic_xml.BaseXmlModel):
    property: None | list[int] = pydantic_xml.wrapped("Property",
      pydantic_xml.element(tag="int"),
    )

Top.from_xml(xml_list_int)
Top.from_xml(xml_none) # Currently fails.

**Comment by dapper91** [comment]
@ReinderVosDeWael Hi,

Add the default value for the property field. This code should work:

```python
class Top(pydantic_xml.BaseXmlModel):
    property: None | list[int] = pydantic_xml.wrapped(
        "Property", pydantic_xml.element(tag="int", default=None),
    )
```

**Comment by ReinderVosDeWael** [comment]
Thanks! That indeed resolved my issue.
