### ISSUE TITLE
default values are not validated against the model

### ISSUE THREAD

**Issue by Gijs-Koot** [dapper91/pydantic-xml#220]
If an `element` or `attribute` has a default value assigned, that value is not validated. This can result in invalid instances, like what happens below. 

```python
        class LineXML(BaseXmlModel, tag="line"):
            length: int = element(tag="length", default=None)

        xml_raw = b"""<?xml version="1.0" encoding="UTF-8"?>
        <line>
        </line>
        """

        line = LineXML.from_xml(xml_raw)

        assert isinstance(line.length, int)  # line.length is now `None`
```

I think it would be more in the spirit of `pydantic` if this triggers a `ValidationError`.

**Comment by dapper91** [comment]
@Gijs-Koot Hi

`pydantic` doesn't validate default values neither. To enable that you should pass `validate_default` flag to config.
https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.validate_default

```python
  class LineXML(BaseXmlModel, tag="line", validate_default=True):
      length: int = element(tag="length", default=None)

  xml_raw = b"""<?xml version="1.0" encoding="UTF-8"?>
  <line>
  </line>
  """

  line = LineXML.from_xml(xml_raw)  # ValidationError raised here

```
