### ISSUE TITLE
Simple model with root namespace on error

### ISSUE THREAD

**Issue by PaulSka** [dapper91/pydantic-xml#226]
Hi,
I try to parse to my model (according to https://pydantic-xml.readthedocs.io/en/stable/pages/quickstart.html#sub-models) with only a root namespace but with no results.

This is XML
`<?xml version="1.0" encoding="UTF-8"?>
<company xmlns="urn:x">
    <headquarters>
        <country>US</country>
        <state>California</state>
        <city>Hawthorne</city>
    </headquarters>
</company>`

And the models
`class Headquarters(BaseXmlModel, tag='headquarters'):
    country: str = element()
    state: str = element()
    city: str = element()

class Company(BaseXmlModel, tag='company', nsmap={'': 'urn:x'}):
    headquarters: Headquarters`

Output on python
`        if field_errors:
>           raise utils.build_validation_error(title=self._model.__name__, errors_map=field_errors)
E           pydantic_core._pydantic_core.ValidationError: 3 validation errors for Company
E           headquarters.country
E             [line -1]: Field required [type=missing, input_value={}, input_type=dict]
E           headquarters.state
E             [line -1]: Field required [type=missing, input_value={}, input_type=dict]
E           headquarters.city
E             [line -1]: Field required [type=missing, input_value={}, input_type=dict]`

How can validate this simple model ?

If i remove namespace and nsmap on xml and model, no problems.

Thanks !

**Comment by dapper91** [comment]
@PaulSka Hi,

Sub-models don't inherit parent model namespace map, it must be defined for each sub-model explicitly:

```python
NSMAP={'': 'urn:x'}

class Headquarters(BaseXmlModel, tag='headquarters', nsmap=NSMAP):
    country: str = element()
    state: str = element()
    city: str = element()

class Company(BaseXmlModel, tag='company', nsmap=NSMAP):
    headquarters: Headquarters
```

**Comment by PaulSka** [comment]
@dapper91 Thanks !
