### ISSUE TITLE
Add option to crash `from_xml` when deserialization fails

### ISSUE THREAD

**Issue by Jacob-Flasheye** [dapper91/pydantic-xml#23]
Hi.

I found this library yesterday and it looks promising for our ($work) use case.
However, there is a small annoyance currently, in that the `from_xml` classmethod will output a `None` when deserialization fails.
IMO, it would be nice if deserialization crashed, pointing to what element of the XML caused the crash.

Is this something you consider worth pursuing? If so, I'm willing to write a PR.

**Comment by dapper91** [comment]
Hi. 

`from_xml` method returns `None` if the root element not found in the provided xml. In other cases it raises an exception with information about which element caused parsing error.

**Comment by Jacob-Flasheye** [comment]
Hi, thank you for the quick reply!

I later figured out exactly what you just mentioned, that here is a difference between unsuccessful parsing and not parsing due to no root element.
What's the reason to return `None` when no root is found?

**Comment by dapper91** [comment]
The library api had been changed in version 0.6.0. It raises an exception instead of returning `None`.
