### ISSUE TITLE
How to handle XML Schema `sequence`, `any`, and `anyAttribute`?

### ISSUE THREAD

**Issue by Jacob-Flasheye** [dapper91/pydantic-xml#24]
Hi.

I'm trying to implement a schema that includes `sequence`, `any`, and `anyAttribute` tags. I am still getting familiar with XML (have worked with JSON data mostly) and I'm not sure how, or if it's even possible currently, to implement such types in this library.

Here are two snippets from the schema file:
```xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema>
  <xs:sequence>
    <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
  <xs:sequence>
  <xs:anyAttribute processContents="lax"/>
</xs:schema>
```

If it is not possible to do, are there any plans to implement this feature? If there is interest, I'm willing to help!

**Comment by sshishov** [comment]
I guess sequence is implemented using `list[...]` and here minOccurs=0 means that it can be omitted, therefore you have to type something like:
```python
class SequenceXmlModel(BaseXmlModel, tag='sequence'):
    sequence_item: list[str] = element()
```
Which will work with:
```xml
<sequence>
    <sequence_item>a</sequence_item>
    <sequence_item>b</sequence_item>
    <sequence_item>c</sequence_item>
</sequence>

RESULT: {'sequence': ['a', 'b', 'c']}
```
and
```xml
<sequence>
</sequence>

RESULT: {'sequence': []}
```
