### ISSUE TITLE
TypeError: Object of type IPv4Address is not XML serializable

### ISSUE THREAD

**Issue by jsenecal** [dapper91/pydantic-xml#29]
When using fields of type "IpvAnyAddress" (`from pydantic import IPvAnyAddress`), serialization to XML raises a `TypeError`.

Please add support for `ipaddress` types.

I will submit a PR to support this.

**Comment by jsenecal** [comment]
I would argue that those types, which are native to both Pydantic and Python should be supported out of the box, just like you opted to support datetime types out of the box.

Thanks for the workaround however.

**Comment by dapper91** [comment]
Sounds reasonable.
