### ISSUE TITLE
Optional fields raise TypeError in XmlEncoder without skip_empty=True

### ISSUE THREAD

**Issue by jsenecal** [dapper91/pydantic-xml#36]
Since the validation for fields that should not be `None` is done by pydantic itself, it seems reasonable to me that `XmlEncoder` should not raise a TypeError in [serializers.py#L58](https://github.com/dapper91/pydantic-xml/blob/master/pydantic_xml/serializers.py#L58) and should instead return "" for those.

Let me know what you think, I can submit a pr if we're on the same page :)

**Comment by GuillaumeDesforges** [comment]
This is indeed not trivial. It should at least be better documented.

**Comment by dapper91** [comment]
Fixed in version 2.x.
