### ISSUE TITLE
Element with attribute in one go

### ISSUE THREAD

**Issue by sshishov** [dapper91/pydantic-xml#47]
Hi dear maintainer.

During using your library I found very inconvenient to create the model if I need to parse element like
```xml
<ParentTag>
    <ChildTag child_attr='attr_value'>tag_value</ChildTag>
</ParentTag>
```

To parse it I have to create the model `ChildTag`:
```python
class ChildTag(BaseXmlModel):
    text: str
    child_attr: str = attr()

class ParentTag(BaseXmlModel)
    child_tag: ChildTag
```

Instead I would like to have something like:
```python
class ParentTag(BaseXmlModel)
    child_tag: dict[str, str] = element('ChildTag', ...)
```

**Comment by reinholdsson** [comment]
Perhaps you could make use of `wrapped`? For example:

```python
from pydantic_xml import BaseXmlModel, wrapped

class ParentTag(BaseXmlModel):
    text: str = wrapped('ChildTag')
    attr: str = wrapped('ChildTag', attr(name="child_attr"))

ParentTag(text="text_value", attr="attr_value").to_xml()
````

```
b'<ParentTag><ChildTag child_attr="attr_value">text_value</ChildTag></ParentTag>'
```

See also https://github.com/dapper91/pydantic-xml/blob/master/tests/test_wrapped.py#L8

**Comment by sshishov** [comment]
@reinholdsson , yes this is completely solves my issue.

Thank you very much for pointin out to the example.
I tried to read the documentation and there I could either create attribute or element, but I did not know that I can specify the same `wrapped` 2 times to solve the issue.

Issue solved, thank you very much!
