### ISSUE TITLE
search_mode not inherited by child models

### ISSUE THREAD

**Issue by Kxnr** [dapper91/pydantic-xml#51]
The `search_mode` attribute, set on a base class, isn't inherited by child models. This may apply to additional settings with default values (currently only `ns_attrs`).

## Minimal Example

```python
from pydantic.utils import to_lower_camel
from pydantic_xml import BaseXmlModel, element

class CustomBaseModel(BaseXmlModel, search_mode="unordered", nsmap={"": "somenamespace"}):
    """Base class to configure options"""

    class Config:
        alias_generator = to_lower_camel


class ChildModel(CustomBaseModel):
    """Root 'real' model describing a document"""

    some_field: str = element()
```

## Expected Behavior

I expect that `ChildModel.__xml_search_mode__ == CustomBaseModel.__xml_search_mode__ == "unordered"`

## Observed Behavior

`ChildModel.__xml_search_mode__` is set to the default of `"strict"` unless `seach_mode` is also passed to `ChildModel`.

I believe this is due to the default value in `__init__subclass__` for `search_mode`. The check `search_mode if search_mode is not None` always evaluates `True` and will never fall back to the `else` condition [here](https://github.com/dapper91/pydantic-xml/blob/184584abe944d28fa33c102d2328dc537ee9144b/pydantic_xml/model.py#L241).

----

New to Open Source contributions so, let me know if there's anything else you need. I'm happy to pull together a PR if this diagnosis seems right. Thanks!

**Comment by dapper91** [comment]
@Kxnr Hi. Thank you for the report. That's a bug. I will fix it in the next update.

**Comment by Kxnr** [comment]
Thanks!

**Comment by Bolik** [comment]
Is it possible to specify search_mode in model config? Like this,

```
class BaseXmlModel(XmlModel):
    class Config:
        anystr_strip_whitespace = True
        underscore_attrs_are_private = True
        search_mode='unordered'
```

**Comment by dapper91** [comment]
@Bolik Hi. No, it is not possible now.
