### ISSUE TITLE
Plans for Pydantic v2?

### ISSUE THREAD

**Issue by sleiner** [dapper91/pydantic-xml#64]
Since the [pydantic 2.0 will likely release very soon](https://github.com/pydantic/pydantic/issues/4887) and will contain quite a few [breaking changes](https://docs.pydantic.dev/dev-v2/migration/), I am wondering what this project's plans are for adopting it.

As an aside: I am not complaining, just checking :-) Thanks for all your work on pydantic-xml!

**Comment by ajoino** [comment]
I'm also very excited for Pydantic 2.0 and I'm willing to help if needed!

**Comment by refundid** [comment]
Same here ✋

**Comment by dapper91** [comment]
I am working on it. pydantic 2.0 has a lot of breaking changes so it could take some time to adopt the library for the new api. I suppose alpha version will be available within a month.

**Comment by dapper91** [comment]
alpha release is available for testing https://pypi.org/project/pydantic-xml/2.0.0a1/

I tried to keep the api where it possible.

**Breaking changes:**

- [custom root type](https://docs.pydantic.dev/latest/usage/models/#rootmodel-and-custom-root-types) declaration has been changed. It must inherit `RootXmlModel` from now on. [See](https://pydantic-xml.readthedocs.io/en/v2.0.0a1/pages/data-binding/models.html#custom-root-type) for more details.
- generic models are no longer inherited from `BaseGenericXmlModel` but from `BaseXmlModel`. [See](https://pydantic-xml.readthedocs.io/en/v2.0.0a1/pages/data-binding/generics.html).
- encoding customization api has been changed. [See](https://pydantic-xml.readthedocs.io/en/v2.0.0a1/pages/misc.html#encoding).


**New features:**

- element attributes can be bound to [TypedDict](https://pydantic-xml.readthedocs.io/en/v2.0.0a1/pages/data-binding/mappings.html#typed-dict)
- similar to pydantic [computed fields](https://docs.pydantic.dev/latest/usage/computed_fields/) it is possible to declare [computed entities](https://pydantic-xml.readthedocs.io/en/v2.0.0a1/pages/misc.html#computed-entities).


[Full Documentation](https://pydantic-xml.readthedocs.io/en/v2.0.0a1/index.html)

**Comment by dapper91** [comment]
pydantic v2 compatible version released.
